// AUTO-GENERATED by scripts/fetch-articles.ts. Do not edit by hand.
//
// This file is the runtime source of truth for the blog renderer. It is
// rewritten on every build by scripts/fetch-articles.ts, which pulls
// published rows from Supabase. The committed copy is a stub containing the
// pre-CMS posts so a fresh checkout (or a build run without SUPABASE_URL
// set) still produces a working site.

import type { BlogPost } from "./blog-posts";

export const BLOG_POSTS: BlogPost[] = [
  {
    "slug": "challenger-300-350-maintenance-guide",
    "title": "Challenger 300 & 350 Maintenance Guide: Inspections, Heavy Events, and Operator Planning",
    "excerpt": "An operator's guide to Challenger 300 and 350 maintenance — inspection intervals, what happens during heavy events, why downtime varies between shops, and how to plan ahead.",
    "category": "Maintenance Guides",
    "date": "2026-05-12",
    "dateDisplay": "May 12, 2026",
    "author": "The Plane Place Aviation Challenger Team",
    "readingTime": "5 min read",
    "hero": {
      "src": "/images/Challenger Posts/hangar-98-Challenger1.jpg",
      "alt": "Bombardier Challenger in Hangar 98 at Plane Place Aviation, Cleburne, TX"
    },
    "sections": [
      {
        "kind": "paragraph",
        "text": "The Bombardier Challenger 300 and Challenger 350 are among the most popular super-midsize business jets in operation today. They are also two of the most maintenance-friendly aircraft in their class when operated under a properly managed inspection program."
      },
      {
        "kind": "paragraph",
        "text": "Because the Challenger 300 and 350 share nearly identical airframes and maintenance philosophies, operators can generally expect the same inspection structure, maintenance intervals, and long-term planning requirements across both aircraft."
      },
      {
        "kind": "paragraph",
        "text": "This guide breaks down the published maintenance intervals, estimated man-hours, and what operators should realistically expect during routine and heavy inspection events."
      },
      {
        "kind": "heading",
        "text": "Understanding the Challenger 300 & 350 Maintenance Program"
      },
      {
        "kind": "paragraph",
        "text": "Both aircraft follow a MSG-3-based maintenance program, meaning inspections are driven by flight hours, calendar time, and aircraft landings. Whichever limit occurs first becomes the controlling inspection requirement."
      },
      {
        "kind": "paragraph",
        "text": "The maintenance program is designed to spread workload across recurring inspection intervals while concentrating larger structural and systems inspections into major long-term events."
      },
      {
        "kind": "paragraph",
        "text": "For operators, understanding where those heavy inspections occur is critical for budgeting downtime, scheduling maintenance, and avoiding surprises."
      },
      {
        "kind": "heading",
        "text": "What Happens During Heavy Challenger Inspections?"
      },
      {
        "kind": "paragraph",
        "text": "The largest maintenance events on the Challenger 300 and 350 occur during the 48-month, 96-month, and 7,500-landing / 192-month inspections."
      },
      {
        "kind": "paragraph",
        "text": "These inspections involve substantially more aircraft disassembly than routine hourly or annual events. Operators should expect:"
      },
      {
        "kind": "takeaways",
        "items": [
          {
            "text": "Cabin, fairings, and cowlings opened for access.",
            "label": "Extensive panel removal"
          },
          {
            "text": "Defined-zone visual checks across the primary structure.",
            "label": "Structural inspections"
          },
          {
            "text": "Eddy current, ultrasonic, and fluorescent-penetrant testing.",
            "label": "NDT inspections"
          },
          {
            "text": "Tank entry, sealant condition, internal component checks.",
            "label": "Fuel tank access and inspection"
          },
          {
            "text": "Time-tracked component audit and overhaul as required.",
            "label": "Landing gear removal, inspection, and LLP verification"
          },
          {
            "text": "Hinges, bearings, rigging, and bonding integrity.",
            "label": "Flight control inspections and checks"
          },
          {
            "text": "Fleet-wide patterns and known problem areas.",
            "label": "Corrosion inspection and treatment"
          },
          {
            "text": "Hydraulics, pressurization, environmental, and electrical bonding.",
            "label": "Detailed systems testing"
          }
        ]
      },
      {
        "alt": "Wing inspection in progress on a Bombardier Challenger at Plane Place Aviation",
        "src": "/images/Challenger Posts/Challenger-Wing-Inspections.jpg",
        "kind": "figure",
        "caption": "Defined-zone wing inspections during a Challenger heavy maintenance event."
      },
      {
        "kind": "paragraph",
        "text": "The 7,500-landing event is generally considered the heaviest scheduled inspection in the aircraft's maintenance program."
      },
      {
        "kind": "paragraph",
        "text": "A well-maintained aircraft with strong records and consistent maintenance history may remain close to published labor estimates. Aircraft with deferred discrepancies, corrosion exposure, incomplete records, or aging interiors often exceed baseline estimates substantially."
      },
      {
        "kind": "heading",
        "text": "Why Challenger Downtime Varies Between Maintenance Shops"
      },
      {
        "kind": "paragraph",
        "text": "Most Challenger inspection man-hours are predictable. What separates maintenance providers is how efficiently they manage findings once the aircraft is opened."
      },
      {
        "kind": "paragraph",
        "text": "During major inspections, additional repairs are common. Structural findings, corrosion, component wear, and wiring discrepancies can quickly extend downtime if the maintenance facility lacks:"
      },
      {
        "kind": "takeaways",
        "items": [
          {
            "text": "Familiarity with the airframe and its known findings.",
            "label": "Challenger-specific experience"
          },
          {
            "text": "Damage-tolerant repairs completed without sending the work out.",
            "label": "In-house structural capability"
          },
          {
            "text": "Existing relationships for landing gear, engines, and components.",
            "label": "Established vendor support"
          },
          {
            "text": "Working knowledge of the task cards and SB compliance.",
            "label": "Familiarity with Bombardier inspection requirements"
          },
          {
            "text": "Proactive parts coordination during the inspection.",
            "label": "Efficient parts sourcing"
          }
        ]
      },
      {
        "alt": "Bombardier Challenger on jacks in the Plane Place Aviation hangar during a scheduled inspection",
        "src": "/images/Challenger Posts/challenger-in-shop.jpg",
        "kind": "figure",
        "caption": "A Challenger in for a scheduled inspection at our Cleburne hangar."
      },
      {
        "kind": "paragraph",
        "text": "Facilities unfamiliar with the Challenger platform often outsource repairs, creating additional downtime through ferry coordination, third-party structural repairs, and delayed parts procurement."
      },
      {
        "kind": "paragraph",
        "text": "For operators, choosing a shop that routinely performs Challenger inspections can significantly reduce schedule disruption during heavy events."
      },
      {
        "kind": "heading",
        "text": "Challenger 300 vs. Challenger 350 Maintenance Differences"
      },
      {
        "kind": "paragraph",
        "text": "From a maintenance planning perspective, the Challenger 300 and Challenger 350 are extremely similar aircraft. However, several differences affect inspection and support requirements:"
      },
      {
        "kind": "heading",
        "text": "Engine Differences"
      },
      {
        "kind": "paragraph",
        "text": "The Challenger 300 uses the Honeywell HTF7000 engine, while the Challenger 350 uses the uprated HTF7350. Although the engines follow a similar maintenance philosophy, the 350 incorporates updated software, engine components, and support considerations."
      },
      {
        "alt": "Honeywell HTF7000 engine on a Bombardier Challenger",
        "src": "/images/Challenger Posts/Challenger-Engine.jpg",
        "kind": "figure",
        "caption": "The Honeywell HTF7000 powers the Challenger 300; the 350 uses the uprated HTF7350 variant."
      },
      {
        "kind": "heading",
        "text": "Avionics Differences"
      },
      {
        "kind": "paragraph",
        "text": "Challenger 350 aircraft introduced Collins Pro Line 21 Advanced avionics, which differs from the earlier Pro Line 21 systems installed in the Challenger 300."
      },
      {
        "kind": "heading",
        "text": "Winglet Configuration"
      },
      {
        "kind": "paragraph",
        "text": "The Challenger 350 introduced canted winglets that slightly alter inspection access and structural inspection requirements."
      },
      {
        "kind": "paragraph",
        "text": "Despite these differences, most maintenance facilities experienced on the Challenger 300 platform can support the Challenger 350 as well."
      },
      {
        "kind": "heading",
        "text": "Planning Ahead for Challenger Heavy Maintenance"
      },
      {
        "kind": "paragraph",
        "text": "Operators approaching a major Challenger inspection should begin planning well in advance. Before scheduling a 48-month, 96-month, 192-month, or 7,500-landing inspection, it is smart to review:"
      },
      {
        "kind": "takeaways",
        "items": [
          {
            "text": "Complete history including any deferred items.",
            "label": "Aircraft maintenance records"
          },
          {
            "text": "Compliance audit ahead of the event.",
            "label": "Open Service Bulletins"
          },
          {
            "text": "Current AD compliance verified.",
            "label": "Airworthiness Directive status"
          },
          {
            "text": "Time-tracked component audit.",
            "label": "Landing gear LLP tracking"
          },
          {
            "text": "Honeywell MSP status and inclusions.",
            "label": "Engine program coverage"
          },
          {
            "text": "Cabin work that bundles cleanly with the visit.",
            "label": "Interior refurbishment needs"
          }
        ]
      },
      {
        "kind": "heading",
        "text": "Why Operators Choose Plane Place Aviation for Challenger Maintenance"
      },
      {
        "kind": "paragraph",
        "text": "Plane Place Aviation focuses exclusively on business aircraft maintenance, including Challenger, Citation, and Hawker platforms."
      },
      {
        "kind": "paragraph",
        "text": "Our team routinely performs Challenger inspections ranging from routine scheduled maintenance to major structural and heavy inspection events."
      },
      {
        "kind": "paragraph",
        "text": "Because Challenger maintenance is part of our daily operation — not an occasional project — we understand the inspection flow, recurring findings, and planning considerations that affect operator downtime."
      },
      {
        "alt": "Plane Place Aviation technician working on a Challenger component at the maintenance workstation",
        "src": "/images/Challenger Posts/Dalton-on-workstation.jpg",
        "kind": "figure",
        "caption": "Challenger work is part of our daily operation in Cleburne."
      },
      {
        "kind": "heading",
        "text": "Frequently Asked Questions"
      },
      {
        "kind": "heading",
        "text": "What is the heaviest scheduled inspection on a Challenger 300 or 350?"
      },
      {
        "kind": "paragraph",
        "text": "The 7,500-landing / 192-month inspection is typically the largest scheduled maintenance event in the program, involving extensive structural inspection and aircraft disassembly."
      },
      {
        "kind": "heading",
        "text": "Are Challenger 300 and Challenger 350 inspections basically the same?"
      },
      {
        "kind": "paragraph",
        "text": "Yes. The aircraft share nearly identical maintenance programs, with only minor differences related to engines, avionics, and winglet configuration."
      },
      {
        "kind": "heading",
        "text": "How often are Challenger maintenance programs updated?"
      },
      {
        "kind": "paragraph",
        "text": "Bombardier periodically revises the Maintenance Planning Document (MPD). Operators should always reference the latest approved revision when planning inspections."
      },
      {
        "kind": "heading",
        "text": "Do heavy inspections always exceed published man-hours?"
      },
      {
        "kind": "paragraph",
        "text": "Not always, but findings discovered during inspection commonly increase labor beyond baseline published estimates."
      },
      {
        "kind": "heading",
        "text": "Final Thoughts"
      },
      {
        "kind": "paragraph",
        "text": "The Challenger 300 and 350 remain some of the most reliable and operationally efficient super-midsize aircraft in business aviation."
      },
      {
        "kind": "paragraph",
        "text": "But like any high-performance aircraft, long-term reliability depends heavily on proactive maintenance planning and choosing a facility experienced with the platform."
      },
      {
        "kind": "paragraph",
        "text": "Understanding inspection intervals, heavy maintenance events, and realistic downtime expectations allows operators to better control maintenance costs and reduce operational disruption."
      }
    ],
    "tags": [
      "Challenger 300",
      "Challenger 350",
      "Maintenance",
      "Inspection",
      "Heavy Maintenance",
      "Operator Planning"
    ],
    "cta": {
      "headline": "Planning a Challenger 300 or 350 maintenance event?",
      "body": "We do Challenger work weekly — send your airframe details and the next scheduled interval, and we'll come back with a scope and a turn target."
    }
  },
  {
    "slug": "challenger-300-main-entry-corrosion",
    "title": "Challenger 300 Main Entry Area Corrosion: Field Insights",
    "excerpt": "A recurring structural pattern in the Challenger 300 fleet — what's driving it, and why operators should catch it before the 192-month inspection turns into a major structural repair.",
    "category": "Field Insights",
    "date": "2026-04-21",
    "dateDisplay": "April 21, 2026",
    "author": "The Plane Place Aviation Structural Team",
    "readingTime": "4 min read",
    "hero": {
      "src": "/blog/images/challenger-300-corrosion/figure-1.png",
      "alt": "Corrosion on the main entry area frame and stringer of a Challenger 300"
    },
    "sections": [
      {
        "kind": "paragraph",
        "text": "Over the past year, we've seen a pattern emerge across the Challenger 300 fleet: heavy corrosion in the main entry area, most often surfacing during the 192-month inspection. This isn't an isolated finding — it's a trend. Left alone, it turns a scheduled inspection into a major structural repair, with the downtime and cost to match."
      },
      {
        "kind": "heading",
        "text": "The problem: hidden corrosion in a high-risk area"
      },
      {
        "alt": "Corrosion identified on the frame and stringer in the main entry area",
        "src": "/blog/images/challenger-300-corrosion/figure-1.png",
        "kind": "figure",
        "caption": "Figure 1. Corrosion identified on the frame and stringer in the main entry area."
      },
      {
        "alt": "Main entry area after cleaning, exposing corrosion",
        "src": "/blog/images/challenger-300-corrosion/figure-2.png",
        "kind": "figure",
        "caption": "Figure 2. Main entry area after cleaning and identifying possible corrosion."
      },
      {
        "kind": "paragraph",
        "text": "Across multiple recent inspections, we've identified heavy corrosion on frames and stringers within the main entry area. The Challenger 300 uses a damage-tolerant structure, which means repairs in this region are highly engineered and generally limited to OEM-approved methods. That makes the work both time-consuming and expensive once it's already there."
      },
      {
        "kind": "heading",
        "text": "Root cause #1: ineffective drainage design"
      },
      {
        "alt": "Water and contamination trapped along the structure due to ineffective drainage routing",
        "src": "/blog/images/challenger-300-corrosion/figure-3.png",
        "kind": "figure",
        "caption": "Figure 3. Water and contamination trapped along the structure due to ineffective drainage routing."
      },
      {
        "kind": "paragraph",
        "text": "The primary driver is water intrusion combined with poor drainage beneath the main entry doorstep. Water pools under the step with no efficient path out. A drain hole exists, but it only starts functioning once water reaches a specific level — and when drainage does occur, it routes water into the middle of the fuselage, soaking the insulation and giving moisture another path to migrate."
      },
      {
        "kind": "paragraph",
        "text": "Bombardier has addressed this with **SB 100-53-36** (Challenger 300) and **SB 350-53-005** (Challenger 350), both aimed at improving drainage in the passenger door area."
      },
      {
        "kind": "heading",
        "text": "Root cause #2: missed findings during scheduled inspections"
      },
      {
        "alt": "Debris and contamination hiding corrosion during a scheduled inspection",
        "src": "/blog/images/challenger-300-corrosion/figure-4.png",
        "kind": "figure",
        "caption": "Figure 4. Debris and contamination can hide corrosion during scheduled inspections."
      },
      {
        "kind": "paragraph",
        "text": "During 48- and 96-month inspections, limited access and inadequate cleaning can mask corrosion that is already present. Bombardier emphasizes proper cleaning and access prior to inspection in **AW300-53-0420** — and it matters. You cannot inspect what you cannot see."
      },
      {
        "kind": "heading",
        "text": "The Plane Place Aviation approach"
      },
      {
        "kind": "paragraph",
        "text": "We've completed several full frame and stringer replacements in the main entry area on Challenger 300s. Our structural team knows this region, and we turn repairs and replacements around quickly. Because the work stays in-house, operators avoid the downtime and resale damage that comes with a major-repair history on the aircraft logs."
      },
      {
        "kind": "heading",
        "text": "Takeaways for operators"
      },
      {
        "kind": "takeaways",
        "items": [
          {
            "text": "Check whether the drainage-improvement SBs have been incorporated on your aircraft.",
            "label": "Verify the service bulletins"
          },
          {
            "text": "Ensure inspections include full access, thorough cleaning, and detailed visual checks — not a quick look through what's already there.",
            "label": "Prioritize access and cleaning"
          },
          {
            "text": "Make sure your maintenance provider has the in-house capability to perform complex structural repairs — not just run the inspection. This is the deciding factor for 48-, 96-, and 192-month events.",
            "label": "Pick a provider who can repair, not just inspect"
          }
        ]
      },
      {
        "kind": "callout",
        "text": "Early detection is the only way to keep a minor maintenance finding from becoming a major structural overhaul."
      }
    ],
    "tags": [
      "Challenger 300",
      "Challenger 350",
      "Corrosion",
      "192-Month Inspection",
      "Structural Repair"
    ],
    "cta": {
      "headline": "Seeing something similar on your aircraft?",
      "body": "We handle Challenger structural work in-house. Send us the squawk or your upcoming inspection scope — we'll tell you what we'd do about it."
    }
  },
  {
    "slug": "plane-place-aviation-receives-mexico-afac-repair-station-certification",
    "title": "Plane Place Aviation Receives Mexico AFAC Repair Station Certification",
    "excerpt": "Plane Place Aviation is now a Mexico AFAC Certified Repair Station, expanding maintenance services for Mexico-registered Challenger, Hawker, and Citation operators.",
    "category": "Company News",
    "date": "2025-08-18",
    "dateDisplay": "August 18, 2025",
    "author": "Plane Place Aviation",
    "readingTime": "2 min read",
    "hero": {
      "src": "/blog/images/plane-place-aviation-receives-mexico-afac-repair-station-certification/hero.jpg",
      "alt": "Plane Place Aviation receives Mexico AFAC certification"
    },
    "sections": [
      {
        "kind": "paragraph",
        "text": "Plane Place Aviation is proud to announce it has been approved by AFAC and is now a Mexico AFAC Certified Repair Station. This achievement marks the ongoing dedication of continued growth, enabling the expansion of capabilities and services to Mexico operators while delivering the highest safety and quality services in the industry."
      },
      {
        "kind": "paragraph",
        "text": "Becoming AFAC certified is a process that affirms a repair station's full compliance with the federal regulations of safety, maintenance, training, and operational oversight. This allows Plane Place to perform maintenance on Mexico-registered aircraft at its Cleburne, Texas location. The hangar facilities offer a prime location, at less than an hour of flight time from the border. Services available include airframe, engine, radio, wheel, tire, battery maintenance, and additional accessory capabilities for Challenger, Hawker, and Citation airframes."
      },
      {
        "kind": "callout",
        "text": "\"We are honored to receive our AFAC certification, which is only accomplished by our team's dedication to excellence and our commitment to provide the highest quality of safety and reliable services to our valued customers.\" — Travis Roberson, VP of Maintenance"
      },
      {
        "kind": "callout",
        "text": "\"We are very excited to become AFAC approved. With our centralized southern location, we are in a prime spot to be the first and only stop for Mexico operators to come for maintenance.\" — Tristan Noe, Director of Maintenance"
      }
    ],
    "tags": [
      "AFAC",
      "Mexico",
      "Certification",
      "Repair Station"
    ]
  },
  {
    "slug": "now-hiring-ap-mechanic-avionics-technician",
    "title": "Now Hiring: A&P Mechanic & Avionics Technician",
    "excerpt": "Plane Place Aviation is hiring experienced A&P mechanics and avionics technicians to support our growing Challenger, Hawker, and Citation maintenance operations in Cleburne, Texas.",
    "category": "Careers",
    "date": "2025-07-01",
    "dateDisplay": "July 1, 2025",
    "author": "Plane Place Aviation",
    "readingTime": "2 min read",
    "hero": {
      "src": "/blog/images/now-hiring-ap-mechanic-avionics-technician/hero.jpg",
      "alt": "Plane Place Aviation hiring A&P mechanics and avionics technicians"
    },
    "sections": [
      {
        "kind": "paragraph",
        "text": "Plane Place Aviation is a growing Part 145 repair station specializing in Challenger, Citation, and Hawker business jets located in Cleburne, TX, just outside the DFW area. The company is expanding its Challenger and super-midsize maintenance services and seeking skilled A&P mechanics interested in building a career."
      },
      {
        "kind": "heading",
        "text": "Position details"
      },
      {
        "kind": "paragraph",
        "text": "Location: Cleburne, TX (south of Fort Worth). Schedule: Full-time M–F with overtime opportunities."
      },
      {
        "kind": "heading",
        "text": "Responsibilities"
      },
      {
        "kind": "paragraph",
        "text": "Performing scheduled and unscheduled maintenance on Challenger, Hawker, and Citation jets, troubleshooting and repairing airframe and powerplant systems, collaborating with experienced technicians, and maintaining FAA and manufacturer standards."
      },
      {
        "kind": "heading",
        "text": "Required qualifications"
      },
      {
        "kind": "paragraph",
        "text": "A&P Certificate, 3+ years of experience on Challenger, Hawker, or Citation jets, strong troubleshooting skills, attention to quality, and ability to read technical manuals and wiring diagrams."
      },
      {
        "kind": "heading",
        "text": "What we offer"
      },
      {
        "kind": "paragraph",
        "text": "Competitive pay, IRA matching, PTO, regular bonuses, employer-covered medical/dental/vision insurance, relocation assistance if needed, and genuine career advancement opportunities including lead roles and quality assurance positions."
      },
      {
        "kind": "callout",
        "text": "Interested? Contact Tristan Noe, Director of Maintenance, at tristan@ppa.aero or (817) 768-8884."
      }
    ],
    "tags": [
      "Careers",
      "Hiring",
      "A&P Mechanic",
      "Avionics"
    ]
  },
  {
    "slug": "plane-place-aviation-expands-operations-with-move-to-larger-hangar-space",
    "title": "Plane Place Aviation Expands Operations with Move to Larger Hangar Space",
    "excerpt": "Plane Place Aviation expands to 40,000 sq ft of hangar space at Cleburne airport — additional capacity for the airframe-specific maintenance our customers depend on.",
    "category": "Company News",
    "date": "2025-03-01",
    "dateDisplay": "March 1, 2025",
    "author": "Plane Place Aviation",
    "readingTime": "1 min read",
    "hero": {
      "src": "/blog/images/plane-place-aviation-expands-operations-with-move-to-larger-hangar-space/hero.jpg",
      "alt": "Plane Place Aviation's newly renovated hangar at Cleburne airport"
    },
    "sections": [
      {
        "kind": "paragraph",
        "text": "Plane Place Aviation is pleased to announce its expansion to a larger, newly renovated hangar facility at Cleburne, TX (KCPT) airport."
      },
      {
        "kind": "paragraph",
        "text": "Plane Place, a Certified Repair Station, expanded to a larger facility to provide additional space for employees and visitors, while also accommodating the growing customer demand for airframe-specific maintenance. The newly acquired and completely renovated hangar brings the company's total to 40,000 sq. ft. of hangar space at Cleburne airport. The facility also includes a comfortable lounge area and ample office space for customers and employees."
      },
      {
        "kind": "callout",
        "text": "\"We're quickly growing and expanding the services we offer, addressing the growing demand for quality maintenance on the airframes we specialize in. This growth can all be attributed to our commitment to provide the best possible service to our customers, backed by our exceptional and specialized team members.\" — Tristan Noe, co-founder"
      }
    ],
    "tags": [
      "Facilities",
      "Cleburne",
      "Expansion"
    ]
  },
  {
    "slug": "plane-place-aviation-adds-new-challenger-604-605-and-650-capabilities",
    "title": "Plane Place Aviation Adds New Challenger 604, 605 and 650 Capabilities",
    "excerpt": "Plane Place Aviation expands Challenger maintenance to the 604, 605, and 650 — adding to existing 300 and 350 capabilities, with 24/7 AOG support across Texas and Oklahoma.",
    "category": "Capabilities",
    "date": "2024-09-01",
    "dateDisplay": "September 1, 2024",
    "author": "Plane Place Aviation",
    "readingTime": "1 min read",
    "hero": {
      "src": "/blog/images/plane-place-aviation-adds-new-challenger-604-605-and-650-capabilities/hero.jpg",
      "alt": "Bombardier Challenger aircraft maintained by Plane Place Aviation"
    },
    "sections": [
      {
        "kind": "paragraph",
        "text": "Plane Place Aviation is pleased to announce the addition of Challenger 604, 605, and 650 to our growing list of maintenance capabilities, which already includes Challenger 300 and 350."
      },
      {
        "kind": "paragraph",
        "text": "The additional capabilities expand the reach of Plane Place's already established support for Hawker and Citation models. With 24/7 AOG support available in Texas and Oklahoma, customers will experience top-tier maintenance, tailored specifically to their aircraft."
      },
      {
        "kind": "callout",
        "text": "\"Our commitment to high-quality maintenance and dedication to customer satisfaction continues to be our focus as we expand our capabilities, ensuring we surpass each customer's expectations with an exceptional experience.\" — Tristan Noe, co-owner"
      },
      {
        "kind": "callout",
        "text": "\"We feel supporting this fleet will help us support our current customer base who are upgrading to the Challenger fleet and also reaching new operators who seek high-quality maintenance.\" — Travis Roberson, co-owner"
      },
      {
        "kind": "heading",
        "text": "We specialize in"
      },
      {
        "kind": "paragraph",
        "text": "**Hawker:** 800, 800XP, 900XP, 1000"
      },
      {
        "kind": "paragraph",
        "text": "**Citation:** 550, 560, 560XL/XLS, 650, 680"
      },
      {
        "kind": "paragraph",
        "text": "**Challenger:** 300, 350, 604, 605, 650"
      }
    ],
    "tags": [
      "Challenger 604",
      "Challenger 605",
      "Challenger 650",
      "Capabilities"
    ]
  },
  {
    "slug": "receives-faa-certification-as-a-part-145-repair-station",
    "title": "Plane Place Aviation Receives FAA Certification as a Part 145 Repair Station",
    "excerpt": "Plane Place Aviation has received FAA Part 145 certification — a milestone enabling expanded service offerings on Hawker, Citation, and Challenger aircraft.",
    "category": "Company News",
    "date": "2024-08-01",
    "dateDisplay": "August 1, 2024",
    "author": "Plane Place Aviation",
    "readingTime": "1 min read",
    "hero": {
      "src": "/blog/images/receives-faa-certification-as-a-part-145-repair-station/hero.jpg",
      "alt": "Plane Place Aviation team at the Cleburne hangar"
    },
    "sections": [
      {
        "kind": "paragraph",
        "text": "Plane Place is pleased to announce it has received FAA certification as a Part 145 repair station."
      },
      {
        "kind": "paragraph",
        "text": "Plane Place, located in Texas, offers an array of services including maintenance and inspections on Hawker, Citation, and Challenger aircraft. This certification will enable Plane Place to expand its service offerings, further establishing the company as a trusted partner in the business aviation industry."
      },
      {
        "kind": "callout",
        "text": "\"With our team's dedication, we are proud to earn this prestigious certification, marking a significant milestone in our commitment to maintain the highest standards of safety, quality, and operational excellence, while ensuring each customer receives an exceptional maintenance experience.\" — Tristan Noe, Owner / Director of Maintenance"
      },
      {
        "kind": "heading",
        "text": "We specialize in"
      },
      {
        "kind": "paragraph",
        "text": "**Hawker:** 800, 800XP, 900XP, 1000"
      },
      {
        "kind": "paragraph",
        "text": "**Citation:** 550, 560, 560XL/XLS, 650, 680"
      },
      {
        "kind": "paragraph",
        "text": "**Challenger:** 300, 350, 604, 605, 650"
      }
    ],
    "tags": [
      "FAA",
      "Part 145",
      "Certification"
    ]
  },
  {
    "slug": "plane-place-aviation-taps-into-surging-demand-for-airframe-mro",
    "title": "Plane Place Aviation Featured in AIN: Tapping into Surging Demand for Airframe MRO",
    "excerpt": "Aviation International News profiles Plane Place Aviation on the heels of expanded AOG and mobile repair team services for Texas and Oklahoma, plus growing onsite support at Dallas Love Field.",
    "category": "Press",
    "date": "2024-04-01",
    "dateDisplay": "April 1, 2024",
    "author": "Plane Place Aviation",
    "readingTime": "2 min read",
    "hero": {
      "src": "/blog/images/plane-place-aviation-taps-into-surging-demand-for-airframe-mro/hero.jpg",
      "alt": "Plane Place Aviation hangar operations"
    },
    "sections": [
      {
        "kind": "paragraph",
        "text": "Aviation International News profiled Plane Place Aviation in April 2024, covering our expansion into AOG and mobile repair team (MRT) services across Texas and Oklahoma, plus growing onsite support at Dallas Love Field."
      },
      {
        "kind": "heading",
        "text": "What the article covered"
      },
      {
        "kind": "paragraph",
        "text": "AIN highlighted Plane Place Aviation's specialization in Bombardier Challenger 300, Hawker, and Cessna Citation airframes, and our focus on supporting large MROs, charter operations, and aircraft management companies. Co-owners Tristan Noe and Travis Roberson discussed the company's growth trajectory two years after founding, the realities of hiring senior technicians in a tight labor market, and the parts-availability and turnaround pressures shaping the broader MRO industry."
      },
      {
        "kind": "callout",
        "text": "\"We've got a lot of customers up there and sometimes it just doesn't make sense for them to fly their airplane down to Cleburne to get minor maintenance done. So, we're trying to provide some support for them up there.\" — Tristan Noe, on the expansion to Dallas Love Field"
      },
      {
        "kind": "paragraph",
        "text": "The full AIN article is available at AINonline. For Plane Place Aviation's current capabilities and AOG response coverage, see our [services page](/services)."
      }
    ],
    "tags": [
      "Press",
      "AIN",
      "MRO",
      "Industry Trends",
      "AOG"
    ]
  }
];
