// Cloudflare Pages Function — serves files from R2 with HMAC signature validation
// Route: /files/:id?expires=<unix_seconds>&signature=<hmac_sha256_url_safe_b64>
//
// The signature is HMAC-SHA256 of `${id}|${expires}` keyed with FILE_SIGNING_SECRET.
// Generated by functions/quote.ts at upload time.

interface R2ObjectBody {
  body: ReadableStream;
  httpMetadata?: {
    contentType?: string;
    contentDisposition?: string;
  };
  customMetadata?: Record<string, string>;
  size: number;
}
interface R2Bucket {
  get(key: string): Promise<R2ObjectBody | null>;
}

interface Env {
  FILE_SIGNING_SECRET: string;
  QUOTE_FILES: R2Bucket;
}

interface PagesContext<E> {
  request: Request;
  env: E;
  params: Record<string, string>;
}
type PagesHandler<E> = (context: PagesContext<E>) => Response | Promise<Response>;

function badRequest(message: string): Response {
  return new Response(message, { status: 400, headers: { "Content-Type": "text/plain" } });
}
function notFound(): Response {
  return new Response("Not found", { status: 404, headers: { "Content-Type": "text/plain" } });
}
function forbidden(message: string): Response {
  return new Response(message, { status: 403, headers: { "Content-Type": "text/plain" } });
}
function gone(message: string): Response {
  return new Response(message, { status: 410, headers: { "Content-Type": "text/plain" } });
}

async function hmacSign(message: string, secret: string): Promise<string> {
  const enc = new TextEncoder();
  const key = await crypto.subtle.importKey(
    "raw",
    enc.encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"]
  );
  const sig = await crypto.subtle.sign("HMAC", key, enc.encode(message));
  const b64 = btoa(String.fromCharCode(...new Uint8Array(sig)));
  return b64.replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

// Constant-time string comparison to prevent timing attacks
function safeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let result = 0;
  for (let i = 0; i < a.length; i++) {
    result |= a.charCodeAt(i) ^ b.charCodeAt(i);
  }
  return result === 0;
}

export const onRequestGet: PagesHandler<Env> = async ({ request, env, params }) => {
  const id = params.id;
  if (!id || !/^[a-f0-9-]{8,64}$/i.test(id)) {
    return badRequest("Invalid file ID");
  }

  const url = new URL(request.url);
  const expiresStr = url.searchParams.get("expires");
  const signature = url.searchParams.get("signature");

  if (!expiresStr || !signature) {
    return badRequest("Missing signature parameters");
  }

  const expires = parseInt(expiresStr, 10);
  if (!Number.isFinite(expires) || expires <= 0) {
    return badRequest("Invalid expires parameter");
  }

  // Check expiry first — cheaper than HMAC
  const now = Math.floor(Date.now() / 1000);
  if (now > expires) {
    return gone("This download link has expired");
  }

  // Verify HMAC signature
  const expectedSig = await hmacSign(`${id}|${expires}`, env.FILE_SIGNING_SECRET);
  if (!safeEqual(signature, expectedSig)) {
    return forbidden("Invalid signature");
  }

  // Fetch from R2
  const r2Key = `attachments/${id}`;
  const obj = await env.QUOTE_FILES.get(r2Key);
  if (!obj) {
    return notFound();
  }

  const filename = obj.customMetadata?.originalFilename || "file";
  const contentType = obj.httpMetadata?.contentType || "application/octet-stream";

  return new Response(obj.body, {
    status: 200,
    headers: {
      "Content-Type": contentType,
      "Content-Disposition": `attachment; filename="${filename.replace(/"/g, "")}"`,
      "Content-Length": String(obj.size),
      "Cache-Control": "private, no-store",
      "X-Content-Type-Options": "nosniff",
    },
  });
};
