import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import { resolve } from 'node:path';
import { cp, mkdir, stat } from 'node:fs/promises';

// Vite configuration for a Chrome MV3 extension.
//
// We emit two top-level inputs:
//   1. `index.html`   — the popup window page that React mounts into.
//   2. `src/background.ts` — the MV3 service worker (must be a flat file at
//      `dist/background.js` so the manifest can reference it directly).
//
// Code-splitting is minimised so the produced `dist/` tree is shallow and
// predictable — Chrome extensions prefer few, well-known files over a
// deeply-chunked SPA build.
//
// A small inline plugin copies `manifest.json` and `icons/` into `dist/`
// at build time so the output directory is directly loadable as an
// unpacked extension with no manual steps.

function copyExtensionStaticAssets(): Plugin {
  return {
    name: 'copy-extension-static-assets',
    apply: 'build',
    async closeBundle() {
      const root = __dirname;
      const outDir = resolve(root, 'dist');

      await mkdir(outDir, { recursive: true });

      // manifest.json — always required.
      await cp(resolve(root, 'manifest.json'), resolve(outDir, 'manifest.json'));

      // icons/ — copy whole folder if present. We don't fail the build if
      // it's missing because icons may be generated by a parallel process.
      const iconsSrc = resolve(root, 'icons');
      try {
        const s = await stat(iconsSrc);
        if (s.isDirectory()) {
          await cp(iconsSrc, resolve(outDir, 'icons'), { recursive: true });
        }
      } catch {
        // No icons/ directory yet — silently skip.
      }
    },
  };
}

export default defineConfig({
  plugins: [react(), copyExtensionStaticAssets()],
  build: {
    outDir: 'dist',
    assetsDir: 'assets',
    emptyOutDir: true,
    sourcemap: false,
    target: 'es2022',
    rollupOptions: {
      input: {
        index: resolve(__dirname, 'index.html'),
        background: resolve(__dirname, 'src/background.ts'),
      },
      output: {
        // Service worker must be ESM and live at a stable path so manifest.json
        // can reference "background.js" by name.
        format: 'es',
        entryFileNames: (chunkInfo) => {
          if (chunkInfo.name === 'background') return 'background.js';
          return 'assets/[name]-[hash].js';
        },
        chunkFileNames: 'assets/[name]-[hash].js',
        assetFileNames: 'assets/[name]-[hash][extname]',
        // Collapse vendor code into the entry chunks so we ship as few files
        // as possible. MV3 service workers also can't dynamically import
        // arbitrary chunks reliably, so a flat output is safer.
        manualChunks: undefined,
      },
    },
  },
});
