/**
 * fetch-articles.ts — pre-build step that pulls published articles from
 * Supabase and writes src/lib/blog-posts.generated.ts. The static Next.js
 * build then consumes the generated file like any other source module.
 *
 * Publish chain:
 *   Publish button (admin UI)
 *     -> POST /admin/api/articles/:id/publish (flips published=true)
 *     -> POST CLOUDFLARE_DEPLOY_WEBHOOK_URL (fires Cloudflare Pages build)
 *     -> Cloudflare Pages runs `npm run build`
 *         -> tsx scripts/fetch-articles.ts  (this file)
 *         -> next build
 *     -> deploy goes live
 *
 * Behavior when SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY are unset:
 *   - Logs a warning, leaves the existing src/lib/blog-posts.generated.ts
 *     in place (committed stub or last-good output), and exits cleanly with
 *     code 0 so a fresh checkout / local build still works.
 *
 * Run manually:
 *   npx tsx scripts/fetch-articles.ts
 */

import { writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { articleToBlogPost, type Article } from "../src/lib/articles-types";
import type { BlogPost } from "../src/lib/blog-posts";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, "..");
const OUTPUT_PATH = resolve(REPO_ROOT, "src/lib/blog-posts.generated.ts");

const HEADER = `// AUTO-GENERATED by scripts/fetch-articles.ts. Do not edit by hand.
//
// This file is the runtime source of truth for the blog renderer. It is
// rewritten on every build by scripts/fetch-articles.ts, which pulls
// published rows from Supabase. The committed copy is a stub containing the
// pre-CMS posts so a fresh checkout (or a build run without SUPABASE_URL
// set) still produces a working site.

import type { BlogPost } from "./blog-posts";

`;

function emitGeneratedFile(posts: BlogPost[]): string {
  // JSON.stringify gives us valid TS literal syntax for plain data (strings,
  // numbers, arrays, plain objects). All BlogPost fields are JSON-safe.
  const literal = JSON.stringify(posts, null, 2);
  return `${HEADER}export const BLOG_POSTS: BlogPost[] = ${literal};\n`;
}

async function fetchPublishedArticles(
  supabaseUrl: string,
  serviceRoleKey: string,
): Promise<Article[]> {
  // Supabase REST: select all columns where published=true, ordered by date desc.
  const url = new URL("/rest/v1/articles", supabaseUrl);
  url.searchParams.set("select", "*");
  url.searchParams.set("published", "eq.true");
  url.searchParams.set("order", "date.desc");

  const res = await fetch(url, {
    headers: {
      apikey: serviceRoleKey,
      Authorization: `Bearer ${serviceRoleKey}`,
      Accept: "application/json",
    },
  });

  if (!res.ok) {
    const body = await res.text().catch(() => "");
    throw new Error(
      `Supabase returned ${res.status} ${res.statusText}: ${body.slice(0, 500)}`,
    );
  }

  return (await res.json()) as Article[];
}

async function main(): Promise<void> {
  const supabaseUrl = process.env.SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!supabaseUrl || !serviceRoleKey) {
    console.warn(
      "[fetch-articles] SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY not set — " +
        "skipping fetch.",
    );
    if (existsSync(OUTPUT_PATH)) {
      console.warn(
        `[fetch-articles] Leaving existing ${OUTPUT_PATH} in place.`,
      );
    } else {
      console.warn(
        `[fetch-articles] No existing generated file — writing empty stub to ${OUTPUT_PATH}.`,
      );
      await writeFile(OUTPUT_PATH, emitGeneratedFile([]), "utf8");
    }
    return;
  }

  console.log("[fetch-articles] Fetching published articles from Supabase...");
  const rows = await fetchPublishedArticles(supabaseUrl, serviceRoleKey);
  console.log(`[fetch-articles] Got ${rows.length} published rows.`);

  const posts = rows.map(articleToBlogPost);
  await writeFile(OUTPUT_PATH, emitGeneratedFile(posts), "utf8");
  console.log(`[fetch-articles] Wrote ${posts.length} posts to ${OUTPUT_PATH}`);
}

main().catch((err) => {
  console.error("[fetch-articles] Failed:", err);
  process.exit(1);
});
